### ISSUE TITLE
Minor error in static-route-ipinfo.io yaml file

### ISSUE THREAD

**Issue by udhay45** [digitalocean/k8s-staticroute-operator#16]
The yaml file has a small typo. Need to change "destination" to "destinations"
➜  examples git:(main) ✗ cat static-route-ipinfo.io.yaml
apiVersion: networking.digitalocean.com/v1
kind: StaticRoute
metadata:
  name: static-route-ipinfo.io
spec:
  destination:
    - "34.117.59.81"

**Comment by v-ctiutiu** [comment]
@udhay45 Thanks for reporting. It is fixed now via https://github.com/digitalocean/k8s-staticroute-operator/commit/1595e1c312ae3b165900e0fe2e93a2bf104f54f5.

Please re-open, if the case. Thanks.
