### ISSUE TITLE
TCP ports

### ISSUE THREAD

**Issue by dmouse** [digitalocean/k8s-staticroute-operator#19]
I have one implementation of egress static route using this document https://github.com/digitalocean/container-blueprints/tree/main/DOKS-Egress-Gateway

but seems like this only works for http request

It is possible use this static route operator for other tcp ports?

**Comment by v-ctiutiu** [comment]
> I have one implementation of egress static route using this document https://github.com/digitalocean/container-blueprints/tree/main/DOKS-Egress-Gateway
> 
> but seems like this only works for http request
> 
> It is possible use this static route operator for other tcp ports?

Hi, sorry for the late reply. Yes, it is possible. It operates at layer 3, hence doesn't care about ports. In essence, your egress gateway acts as a router for your DOKS cluster for each configured path.

**Comment by dmouse** [comment]
thanks, was an issue with my StaticRoute file
